import { Footer } from '@/components/form/Footer'
import './globals.css'
import { Header } from '@/components/form/Header'
import { Provider } from '@/components/form/Provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <div style={{ display: "flex", justifyContent: "center", alignItems: "center", overflow: "auto" }}>
            {children}
          </div>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
